---
- name: Configurar Servidor Debian Basico
  # Host debe coincidir con lo creado en keyed_groups: del archivo azure_rm.yml
  hosts: tag_debian_lab
  remote_user: debianadmin
  become: true 
  gather_facts: true
  vars:
    ssh_port: "5022"

  tasks:
    - name: Cambiar el puerto por defecto de SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port\s'
        line: "Port {{ ssh_port }}"
        state: present
      notify: Reiniciar SSH

    - name: Bloquear el acceso SSH al usuario root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s'
        line: "PermitRootLogin no"
        state: present
      notify: Reiniciar SSH

    - name: Deshabilitar la autenticación por contraseña
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s'
        line: "PasswordAuthentication no"
        state: present
      notify: Reiniciar SSH

    - name: Asegurar que la autenticación por clave pública esté permitida
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication\s'
        line: "PubkeyAuthentication yes"
        state: present
      notify: Reiniciar SSH

    - name: Actualizar la cache de apt (apt update)
      ansible.builtin.apt:
        update_cache: true

    - name: Instalar paquetes esenciales de administracion
      apt:
        name:
          - htop
          - curl
          - git
          - ufw
        state: present

    - name: Crear un archivo de prueba en el servidor
      copy:
        content: "Servidor Debian configurado exitosamente por Ansible desde GitHub Actions en 2026.\n"
        dest: /var/www_welcome.txt
        mode: '0644'



  handlers:
    - name: Reiniciar SSH
      ansible.builtin.service:
        name: ssh
        state: restarted